/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.9.9
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDateEdit>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableView>
#include <QtWidgets/QWidget>
#include "qcustomplot.h"

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QStackedWidget *stackedWidget;
    QWidget *page;
    QTabWidget *tabWidget;
    QWidget *tab_2;
    QGroupBox *groupBox_8;
    QLabel *label_8;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QLineEdit *le_idc;
    QLineEdit *le_nom;
    QLineEdit *le_prenom;
    QLineEdit *le_adresse;
    QPushButton *pb_ajouter;
    QLineEdit *le_nbticket;
    QLabel *label_13;
    QPushButton *pb_modifier;
    QLabel *label_14;
    QLineEdit *le_age;
    QGroupBox *groupBox_9;
    QTableView *tab_client;
    QGroupBox *groupBox_10;
    QLabel *label_15;
    QLineEdit *le_idc_supp;
    QPushButton *pb_supprimer;
    QGroupBox *groupBox_12;
    QLabel *label_16;
    QPushButton *pb_rechercherclient;
    QLineEdit *le_recherche;
    QGroupBox *groupBox_13;
    QPushButton *pb_send;
    QLineEdit *lineEdit;
    QPushButton *pb_export_excel;
    QPushButton *pb_trierclient;
    QWidget *tab_4;
    QCustomPlot *plot;
    QWidget *page_4;
    QTabWidget *tabWidget_4;
    QWidget *tab_7;
    QGroupBox *groupBox_7;
    QLabel *label_25;
    QLabel *label_26;
    QLineEdit *le_adresse_2;
    QLineEdit *le_capacite;
    QLabel *label_27;
    QPushButton *pb_ajouter_station;
    QLabel *label_28;
    QLineEdit *le_region;
    QComboBox *comboBox_nom;
    QGroupBox *groupBox_15;
    QLabel *label_29;
    QLineEdit *le_nom_supp;
    QPushButton *pb_supprimer_station;
    QGroupBox *groupBox_16;
    QTableView *tab_station;
    QComboBox *comboBox_affichage;
    QLineEdit *lr_rechercher_nom;
    QLineEdit *lr_rechercher_capacite;
    QLabel *label_30;
    QLabel *label_31;
    QLabel *label_32;
    QLineEdit *lr_rechercher_region;
    QCheckBox *checkBox_nom;
    QCheckBox *checkBox_capacite;
    QCheckBox *checkBox_region;
    QPushButton *pb_recherche;
    QPushButton *pb_tri_station;
    QGroupBox *groupBox_17;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_36;
    QLineEdit *ln_region;
    QLineEdit *ln_adresse;
    QLineEdit *ln_capacite;
    QPushButton *pb_modifier_station;
    QComboBox *comboBox_nom_2;
    QWidget *tab_8;
    QCustomPlot *plot_4;
    QWidget *page_2;
    QTabWidget *tabWidget_2;
    QWidget *tab;
    QGroupBox *groupBox;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_7;
    QLineEdit *le_id;
    QLineEdit *le_nom_2;
    QLineEdit *le_prenom_2;
    QLineEdit *le_heures;
    QLineEdit *le_type;
    QLineEdit *le_salaire;
    QPushButton *pb_ajouter_2;
    QLineEdit *le_heures_max;
    QLabel *label_6;
    QPushButton *pb_modifier_2;
    QGroupBox *groupBox_2;
    QLabel *label_17;
    QLineEdit *le_id_supp;
    QPushButton *pb_supprimer_2;
    QGroupBox *groupBox_4;
    QLineEdit *le_nom_rech;
    QPushButton *pb_rechercher;
    QLabel *label_9;
    QGroupBox *groupBox_5;
    QPushButton *pb_tri_nom;
    QGroupBox *groupBox_6;
    QPushButton *pushButton;
    QGroupBox *groupBox_3;
    QTableView *tab_personnel;
    QPushButton *chatBtn;
    QWidget *tab_3;
    QCustomPlot *plot_2;
    QWidget *page_3;
    QTabWidget *tabWidget_3;
    QWidget *tab_5;
    QWidget *widget;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_20;
    QLabel *label_21;
    QLabel *label_22;
    QPushButton *ajouter;
    QLineEdit *nbr_places;
    QLineEdit *le_kilometrage;
    QLineEdit *nbr_passagers;
    QPushButton *pb_modifier_3;
    QPushButton *pb_supprimer_3;
    QLineEdit *la_matricule;
    QPushButton *AFFECTER;
    QComboBox *comboBox;
    QLabel *label_23;
    QLabel *label_24;
    QPushButton *pb_trier_matricule;
    QPushButton *pb_rechercher_2;
    QTableView *tableView;
    QPushButton *pb_pdf_2;
    QWidget *tab_6;
    QCustomPlot *plot_3;
    QWidget *page_5;
    QTabWidget *tabWidget_5;
    QWidget *widget_2;
    QGroupBox *groupBox_18;
    QLabel *label_37;
    QLabel *label_38;
    QLabel *label_39;
    QLabel *label_40;
    QLabel *label_41;
    QLineEdit *lineEdit_code;
    QLineEdit *lineEdit_id;
    QLineEdit *lineEdit_redandance;
    QPushButton *pb_ajouter_trajet;
    QLabel *label_42;
    QDateEdit *dateEdit;
    QComboBox *comboBox_3;
    QComboBox *comboBox_4;
    QLabel *label_43;
    QLabel *label_44;
    QWidget *widget_3;
    QTableView *tableView_2;
    QPushButton *modifier;
    QLabel *label_45;
    QLabel *label_46;
    QLabel *label_47;
    QLabel *label_48;
    QLabel *label_49;
    QLineEdit *lineEdit_id_2;
    QLineEdit *lineEdit_code_2;
    QLineEdit *lineEdit_red;
    QPushButton *pushButton_trier_trajet;
    QComboBox *comboBox_2;
    QPushButton *pushButton_rechercher_trajet;
    QDateEdit *dateEdit_2;
    QLabel *label_50;
    QPushButton *pushButton_exporter_trajet;
    QPushButton *pushButton_qrcode_trajet;
    QComboBox *comboBox_5;
    QComboBox *comboBox_6;
    QLabel *label_51;
    QLabel *label_52;
    QLabel *label_qrcode;
    QWidget *tab_9;
    QLabel *label_53;
    QLineEdit *lineEdit_2;
    QPushButton *supprimer;
    QWidget *tab_10;
    QWidget *widget_4;
    QWidget *page_6;
    QTabWidget *tabWidget_6;
    QWidget *Ajouter;
    QGroupBox *groupBox_19;
    QLabel *label_54;
    QLabel *label_55;
    QLabel *label_56;
    QLabel *label_57;
    QLineEdit *le_ID;
    QLineEdit *le_Prix;
    QLineEdit *le_Horaire_entr;
    QLineEdit *le_Horaire_arr;
    QPushButton *pb_ajouter_4;
    QLineEdit *le_ID_2;
    QLineEdit *le_Prix_2;
    QLineEdit *le_Horaire_entr_2;
    QLineEdit *le_Horaire_arr_2;
    QPushButton *pb_modifier_5;
    QLabel *label_58;
    QLabel *label_59;
    QLabel *label_60;
    QLabel *label_61;
    QTableView *tab_ticket_2;
    QPushButton *pb_supp_2;
    QPushButton *pb_recherche_ID_2;
    QLineEdit *lineEdit_3;
    QPushButton *pb_recherche_PRIX_2;
    QLineEdit *lineEdit_4;
    QPushButton *pb_recherche_horaire_entr_2;
    QLineEdit *lineEdit_5;
    QPushButton *on_pb_trier_ticket;
    QComboBox *comboBox_7;
    QPushButton *ticketVIP;
    QWidget *tab_11;
    QCustomPlot *plot_5;
    QPushButton *gestionmetro;
    QPushButton *gestionstation;
    QPushButton *gestionticket;
    QPushButton *gestionclient;
    QPushButton *gestionpersonnel;
    QPushButton *gestiontrajet;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(1479, 750);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QStringLiteral("centralwidget"));
        stackedWidget = new QStackedWidget(centralwidget);
        stackedWidget->setObjectName(QStringLiteral("stackedWidget"));
        stackedWidget->setGeometry(QRect(90, 50, 1331, 671));
        page = new QWidget();
        page->setObjectName(QStringLiteral("page"));
        tabWidget = new QTabWidget(page);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(0, 0, 1331, 681));
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        groupBox_8 = new QGroupBox(tab_2);
        groupBox_8->setObjectName(QStringLiteral("groupBox_8"));
        groupBox_8->setGeometry(QRect(30, 20, 471, 351));
        label_8 = new QLabel(groupBox_8);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(30, 40, 71, 16));
        label_10 = new QLabel(groupBox_8);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(30, 140, 51, 20));
        label_11 = new QLabel(groupBox_8);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(30, 200, 56, 16));
        label_12 = new QLabel(groupBox_8);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(30, 250, 61, 16));
        le_idc = new QLineEdit(groupBox_8);
        le_idc->setObjectName(QStringLiteral("le_idc"));
        le_idc->setGeometry(QRect(150, 40, 113, 22));
        le_nom = new QLineEdit(groupBox_8);
        le_nom->setObjectName(QStringLiteral("le_nom"));
        le_nom->setGeometry(QRect(150, 140, 113, 22));
        le_prenom = new QLineEdit(groupBox_8);
        le_prenom->setObjectName(QStringLiteral("le_prenom"));
        le_prenom->setGeometry(QRect(150, 190, 113, 22));
        le_adresse = new QLineEdit(groupBox_8);
        le_adresse->setObjectName(QStringLiteral("le_adresse"));
        le_adresse->setGeometry(QRect(150, 240, 113, 22));
        pb_ajouter = new QPushButton(groupBox_8);
        pb_ajouter->setObjectName(QStringLiteral("pb_ajouter"));
        pb_ajouter->setGeometry(QRect(270, 310, 93, 28));
        le_nbticket = new QLineEdit(groupBox_8);
        le_nbticket->setObjectName(QStringLiteral("le_nbticket"));
        le_nbticket->setGeometry(QRect(150, 290, 113, 22));
        label_13 = new QLabel(groupBox_8);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(20, 290, 111, 16));
        pb_modifier = new QPushButton(groupBox_8);
        pb_modifier->setObjectName(QStringLiteral("pb_modifier"));
        pb_modifier->setGeometry(QRect(390, 310, 93, 28));
        label_14 = new QLabel(groupBox_8);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(30, 90, 56, 16));
        le_age = new QLineEdit(groupBox_8);
        le_age->setObjectName(QStringLiteral("le_age"));
        le_age->setGeometry(QRect(150, 90, 113, 22));
        groupBox_9 = new QGroupBox(tab_2);
        groupBox_9->setObjectName(QStringLiteral("groupBox_9"));
        groupBox_9->setGeometry(QRect(530, 20, 711, 511));
        tab_client = new QTableView(groupBox_9);
        tab_client->setObjectName(QStringLiteral("tab_client"));
        tab_client->setGeometry(QRect(20, 30, 671, 461));
        groupBox_10 = new QGroupBox(tab_2);
        groupBox_10->setObjectName(QStringLiteral("groupBox_10"));
        groupBox_10->setGeometry(QRect(30, 380, 181, 121));
        label_15 = new QLabel(groupBox_10);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(10, 40, 81, 21));
        le_idc_supp = new QLineEdit(groupBox_10);
        le_idc_supp->setObjectName(QStringLiteral("le_idc_supp"));
        le_idc_supp->setGeometry(QRect(80, 40, 91, 22));
        pb_supprimer = new QPushButton(groupBox_10);
        pb_supprimer->setObjectName(QStringLiteral("pb_supprimer"));
        pb_supprimer->setGeometry(QRect(80, 70, 93, 28));
        groupBox_12 = new QGroupBox(tab_2);
        groupBox_12->setObjectName(QStringLiteral("groupBox_12"));
        groupBox_12->setGeometry(QRect(210, 380, 161, 121));
        label_16 = new QLabel(groupBox_12);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(10, 60, 56, 16));
        pb_rechercherclient = new QPushButton(groupBox_12);
        pb_rechercherclient->setObjectName(QStringLiteral("pb_rechercherclient"));
        pb_rechercherclient->setGeometry(QRect(30, 70, 93, 31));
        le_recherche = new QLineEdit(groupBox_12);
        le_recherche->setObjectName(QStringLiteral("le_recherche"));
        le_recherche->setGeometry(QRect(20, 40, 113, 22));
        groupBox_13 = new QGroupBox(tab_2);
        groupBox_13->setObjectName(QStringLiteral("groupBox_13"));
        groupBox_13->setGeometry(QRect(380, 380, 131, 121));
        pb_send = new QPushButton(groupBox_13);
        pb_send->setObjectName(QStringLiteral("pb_send"));
        pb_send->setGeometry(QRect(20, 70, 93, 28));
        lineEdit = new QLineEdit(groupBox_13);
        lineEdit->setObjectName(QStringLiteral("lineEdit"));
        lineEdit->setGeometry(QRect(10, 40, 113, 22));
        pb_export_excel = new QPushButton(tab_2);
        pb_export_excel->setObjectName(QStringLiteral("pb_export_excel"));
        pb_export_excel->setGeometry(QRect(240, 510, 93, 28));
        pb_trierclient = new QPushButton(tab_2);
        pb_trierclient->setObjectName(QStringLiteral("pb_trierclient"));
        pb_trierclient->setGeometry(QRect(110, 510, 93, 28));
        tabWidget->addTab(tab_2, QString());
        tab_4 = new QWidget();
        tab_4->setObjectName(QStringLiteral("tab_4"));
        plot = new QCustomPlot(tab_4);
        plot->setObjectName(QStringLiteral("plot"));
        plot->setGeometry(QRect(20, 20, 1321, 571));
        tabWidget->addTab(tab_4, QString());
        stackedWidget->addWidget(page);
        page_4 = new QWidget();
        page_4->setObjectName(QStringLiteral("page_4"));
        tabWidget_4 = new QTabWidget(page_4);
        tabWidget_4->setObjectName(QStringLiteral("tabWidget_4"));
        tabWidget_4->setGeometry(QRect(-20, 0, 1281, 621));
        tab_7 = new QWidget();
        tab_7->setObjectName(QStringLiteral("tab_7"));
        groupBox_7 = new QGroupBox(tab_7);
        groupBox_7->setObjectName(QStringLiteral("groupBox_7"));
        groupBox_7->setGeometry(QRect(40, 10, 431, 281));
        label_25 = new QLabel(groupBox_7);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(25, 60, 71, 20));
        label_26 = new QLabel(groupBox_7);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(30, 170, 71, 20));
        le_adresse_2 = new QLineEdit(groupBox_7);
        le_adresse_2->setObjectName(QStringLiteral("le_adresse_2"));
        le_adresse_2->setGeometry(QRect(160, 170, 113, 22));
        le_capacite = new QLineEdit(groupBox_7);
        le_capacite->setObjectName(QStringLiteral("le_capacite"));
        le_capacite->setGeometry(QRect(160, 230, 113, 22));
        label_27 = new QLabel(groupBox_7);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(30, 230, 71, 20));
        pb_ajouter_station = new QPushButton(groupBox_7);
        pb_ajouter_station->setObjectName(QStringLiteral("pb_ajouter_station"));
        pb_ajouter_station->setGeometry(QRect(330, 130, 93, 28));
        label_28 = new QLabel(groupBox_7);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(30, 110, 56, 16));
        le_region = new QLineEdit(groupBox_7);
        le_region->setObjectName(QStringLiteral("le_region"));
        le_region->setGeometry(QRect(160, 110, 113, 22));
        comboBox_nom = new QComboBox(groupBox_7);
        comboBox_nom->setObjectName(QStringLiteral("comboBox_nom"));
        comboBox_nom->setGeometry(QRect(160, 60, 111, 22));
        groupBox_15 = new QGroupBox(tab_7);
        groupBox_15->setObjectName(QStringLiteral("groupBox_15"));
        groupBox_15->setGeometry(QRect(470, 10, 541, 171));
        label_29 = new QLabel(groupBox_15);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(50, 100, 56, 16));
        le_nom_supp = new QLineEdit(groupBox_15);
        le_nom_supp->setObjectName(QStringLiteral("le_nom_supp"));
        le_nom_supp->setGeometry(QRect(130, 100, 113, 22));
        pb_supprimer_station = new QPushButton(groupBox_15);
        pb_supprimer_station->setObjectName(QStringLiteral("pb_supprimer_station"));
        pb_supprimer_station->setGeometry(QRect(290, 100, 93, 28));
        groupBox_16 = new QGroupBox(tab_7);
        groupBox_16->setObjectName(QStringLiteral("groupBox_16"));
        groupBox_16->setGeometry(QRect(470, 180, 671, 391));
        tab_station = new QTableView(groupBox_16);
        tab_station->setObjectName(QStringLiteral("tab_station"));
        tab_station->setGeometry(QRect(20, 30, 531, 191));
        comboBox_affichage = new QComboBox(groupBox_16);
        comboBox_affichage->setObjectName(QStringLiteral("comboBox_affichage"));
        comboBox_affichage->setGeometry(QRect(350, 260, 191, 22));
        lr_rechercher_nom = new QLineEdit(groupBox_16);
        lr_rechercher_nom->setObjectName(QStringLiteral("lr_rechercher_nom"));
        lr_rechercher_nom->setGeometry(QRect(120, 230, 113, 22));
        lr_rechercher_capacite = new QLineEdit(groupBox_16);
        lr_rechercher_capacite->setObjectName(QStringLiteral("lr_rechercher_capacite"));
        lr_rechercher_capacite->setGeometry(QRect(120, 260, 113, 22));
        label_30 = new QLabel(groupBox_16);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(50, 230, 56, 16));
        label_31 = new QLabel(groupBox_16);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(50, 260, 56, 16));
        label_32 = new QLabel(groupBox_16);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(50, 290, 56, 16));
        lr_rechercher_region = new QLineEdit(groupBox_16);
        lr_rechercher_region->setObjectName(QStringLiteral("lr_rechercher_region"));
        lr_rechercher_region->setGeometry(QRect(120, 290, 113, 22));
        checkBox_nom = new QCheckBox(groupBox_16);
        checkBox_nom->setObjectName(QStringLiteral("checkBox_nom"));
        checkBox_nom->setGeometry(QRect(240, 230, 83, 20));
        checkBox_capacite = new QCheckBox(groupBox_16);
        checkBox_capacite->setObjectName(QStringLiteral("checkBox_capacite"));
        checkBox_capacite->setGeometry(QRect(240, 260, 83, 20));
        checkBox_region = new QCheckBox(groupBox_16);
        checkBox_region->setObjectName(QStringLiteral("checkBox_region"));
        checkBox_region->setGeometry(QRect(240, 290, 83, 20));
        pb_recherche = new QPushButton(groupBox_16);
        pb_recherche->setObjectName(QStringLiteral("pb_recherche"));
        pb_recherche->setGeometry(QRect(130, 320, 93, 28));
        pb_tri_station = new QPushButton(groupBox_16);
        pb_tri_station->setObjectName(QStringLiteral("pb_tri_station"));
        pb_tri_station->setGeometry(QRect(450, 330, 93, 28));
        groupBox_17 = new QGroupBox(tab_7);
        groupBox_17->setObjectName(QStringLiteral("groupBox_17"));
        groupBox_17->setGeometry(QRect(40, 300, 441, 281));
        label_33 = new QLabel(groupBox_17);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(40, 70, 56, 16));
        label_34 = new QLabel(groupBox_17);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(40, 170, 61, 20));
        label_35 = new QLabel(groupBox_17);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(40, 120, 71, 20));
        label_36 = new QLabel(groupBox_17);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(45, 220, 71, 20));
        ln_region = new QLineEdit(groupBox_17);
        ln_region->setObjectName(QStringLiteral("ln_region"));
        ln_region->setGeometry(QRect(120, 120, 113, 22));
        ln_adresse = new QLineEdit(groupBox_17);
        ln_adresse->setObjectName(QStringLiteral("ln_adresse"));
        ln_adresse->setGeometry(QRect(120, 170, 113, 22));
        ln_capacite = new QLineEdit(groupBox_17);
        ln_capacite->setObjectName(QStringLiteral("ln_capacite"));
        ln_capacite->setGeometry(QRect(120, 220, 113, 22));
        pb_modifier_station = new QPushButton(groupBox_17);
        pb_modifier_station->setObjectName(QStringLiteral("pb_modifier_station"));
        pb_modifier_station->setGeometry(QRect(310, 150, 93, 28));
        comboBox_nom_2 = new QComboBox(groupBox_17);
        comboBox_nom_2->setObjectName(QStringLiteral("comboBox_nom_2"));
        comboBox_nom_2->setGeometry(QRect(120, 70, 111, 22));
        tabWidget_4->addTab(tab_7, QString());
        tab_8 = new QWidget();
        tab_8->setObjectName(QStringLiteral("tab_8"));
        plot_4 = new QCustomPlot(tab_8);
        plot_4->setObjectName(QStringLiteral("plot_4"));
        plot_4->setGeometry(QRect(40, 60, 981, 541));
        tabWidget_4->addTab(tab_8, QString());
        stackedWidget->addWidget(page_4);
        page_2 = new QWidget();
        page_2->setObjectName(QStringLiteral("page_2"));
        tabWidget_2 = new QTabWidget(page_2);
        tabWidget_2->setObjectName(QStringLiteral("tabWidget_2"));
        tabWidget_2->setGeometry(QRect(-10, 0, 1271, 651));
        tabWidget_2->setStyleSheet(QLatin1String("background-color: rgb(140, 140, 140);\n"
"background-color: rgb(255, 255, 255);"));
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        groupBox = new QGroupBox(tab);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(20, 10, 521, 401));
        groupBox->setStyleSheet(QLatin1String("background-color: rgb(255, 170, 255);\n"
"background-color: rgb(255, 170, 255);\n"
"background-color: rgb(255, 170, 255);\n"
"background-color: rgb(255, 255, 255);"));
        label = new QLabel(groupBox);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(10, 30, 101, 31));
        label_2 = new QLabel(groupBox);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(10, 100, 56, 16));
        label_3 = new QLabel(groupBox);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(10, 170, 56, 16));
        label_4 = new QLabel(groupBox);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(10, 210, 161, 16));
        label_5 = new QLabel(groupBox);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(10, 260, 101, 16));
        label_7 = new QLabel(groupBox);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(10, 300, 91, 31));
        le_id = new QLineEdit(groupBox);
        le_id->setObjectName(QStringLiteral("le_id"));
        le_id->setGeometry(QRect(190, 50, 113, 22));
        le_nom_2 = new QLineEdit(groupBox);
        le_nom_2->setObjectName(QStringLiteral("le_nom_2"));
        le_nom_2->setGeometry(QRect(190, 100, 113, 22));
        le_prenom_2 = new QLineEdit(groupBox);
        le_prenom_2->setObjectName(QStringLiteral("le_prenom_2"));
        le_prenom_2->setGeometry(QRect(190, 150, 113, 22));
        le_heures = new QLineEdit(groupBox);
        le_heures->setObjectName(QStringLiteral("le_heures"));
        le_heures->setGeometry(QRect(190, 210, 113, 22));
        le_type = new QLineEdit(groupBox);
        le_type->setObjectName(QStringLiteral("le_type"));
        le_type->setGeometry(QRect(190, 250, 113, 22));
        le_salaire = new QLineEdit(groupBox);
        le_salaire->setObjectName(QStringLiteral("le_salaire"));
        le_salaire->setGeometry(QRect(190, 300, 113, 22));
        pb_ajouter_2 = new QPushButton(groupBox);
        pb_ajouter_2->setObjectName(QStringLiteral("pb_ajouter_2"));
        pb_ajouter_2->setGeometry(QRect(390, 210, 91, 31));
        le_heures_max = new QLineEdit(groupBox);
        le_heures_max->setObjectName(QStringLiteral("le_heures_max"));
        le_heures_max->setGeometry(QRect(190, 360, 113, 22));
        label_6 = new QLabel(groupBox);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(10, 370, 171, 16));
        pb_modifier_2 = new QPushButton(groupBox);
        pb_modifier_2->setObjectName(QStringLiteral("pb_modifier_2"));
        pb_modifier_2->setGeometry(QRect(390, 310, 101, 41));
        groupBox_2 = new QGroupBox(tab);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(10, 420, 401, 151));
        groupBox_2->setStyleSheet(QLatin1String("background-color: rgb(255, 170, 255);\n"
"background-color: rgb(255, 255, 255);"));
        label_17 = new QLabel(groupBox_2);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(30, 60, 51, 16));
        le_id_supp = new QLineEdit(groupBox_2);
        le_id_supp->setObjectName(QStringLiteral("le_id_supp"));
        le_id_supp->setGeometry(QRect(130, 60, 121, 22));
        pb_supprimer_2 = new QPushButton(groupBox_2);
        pb_supprimer_2->setObjectName(QStringLiteral("pb_supprimer_2"));
        pb_supprimer_2->setGeometry(QRect(300, 60, 81, 31));
        groupBox_4 = new QGroupBox(tab);
        groupBox_4->setObjectName(QStringLiteral("groupBox_4"));
        groupBox_4->setGeometry(QRect(420, 430, 331, 161));
        groupBox_4->setStyleSheet(QLatin1String("background-color: rgb(255, 170, 255);\n"
"background-color: rgb(255, 255, 255);"));
        le_nom_rech = new QLineEdit(groupBox_4);
        le_nom_rech->setObjectName(QStringLiteral("le_nom_rech"));
        le_nom_rech->setGeometry(QRect(80, 30, 113, 22));
        pb_rechercher = new QPushButton(groupBox_4);
        pb_rechercher->setObjectName(QStringLiteral("pb_rechercher"));
        pb_rechercher->setGeometry(QRect(220, 30, 111, 28));
        label_9 = new QLabel(groupBox_4);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(20, 30, 56, 16));
        groupBox_5 = new QGroupBox(tab);
        groupBox_5->setObjectName(QStringLiteral("groupBox_5"));
        groupBox_5->setGeometry(QRect(760, 420, 301, 151));
        groupBox_5->setStyleSheet(QLatin1String("background-color: rgb(255, 170, 255);\n"
"background-color: rgb(255, 255, 255);"));
        pb_tri_nom = new QPushButton(groupBox_5);
        pb_tri_nom->setObjectName(QStringLiteral("pb_tri_nom"));
        pb_tri_nom->setGeometry(QRect(70, 40, 93, 28));
        groupBox_6 = new QGroupBox(tab);
        groupBox_6->setObjectName(QStringLiteral("groupBox_6"));
        groupBox_6->setGeometry(QRect(1070, 420, 181, 131));
        groupBox_6->setStyleSheet(QLatin1String("background-color: rgb(255, 170, 255);\n"
"background-color: rgb(255, 255, 255);"));
        pushButton = new QPushButton(groupBox_6);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(30, 50, 93, 28));
        groupBox_3 = new QGroupBox(tab);
        groupBox_3->setObjectName(QStringLiteral("groupBox_3"));
        groupBox_3->setGeometry(QRect(550, 10, 701, 401));
        tab_personnel = new QTableView(groupBox_3);
        tab_personnel->setObjectName(QStringLiteral("tab_personnel"));
        tab_personnel->setGeometry(QRect(10, 20, 681, 371));
        chatBtn = new QPushButton(tab);
        chatBtn->setObjectName(QStringLiteral("chatBtn"));
        chatBtn->setGeometry(QRect(1150, 560, 93, 28));
        tabWidget_2->addTab(tab, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QStringLiteral("tab_3"));
        plot_2 = new QCustomPlot(tab_3);
        plot_2->setObjectName(QStringLiteral("plot_2"));
        plot_2->setGeometry(QRect(120, 30, 731, 441));
        tabWidget_2->addTab(tab_3, QString());
        stackedWidget->addWidget(page_2);
        page_3 = new QWidget();
        page_3->setObjectName(QStringLiteral("page_3"));
        tabWidget_3 = new QTabWidget(page_3);
        tabWidget_3->setObjectName(QStringLiteral("tabWidget_3"));
        tabWidget_3->setGeometry(QRect(40, 20, 1071, 551));
        tabWidget_3->setStyleSheet(QLatin1String("alternate-background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(231, 255, 239);"));
        tab_5 = new QWidget();
        tab_5->setObjectName(QStringLiteral("tab_5"));
        widget = new QWidget(tab_5);
        widget->setObjectName(QStringLiteral("widget"));
        widget->setGeometry(QRect(40, 50, 401, 461));
        widget->setStyleSheet(QStringLiteral("background-color: rgb(0, 255, 255);"));
        label_18 = new QLabel(widget);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(30, 20, 131, 31));
        label_19 = new QLabel(widget);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(30, 170, 71, 21));
        label_20 = new QLabel(widget);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(30, 220, 91, 21));
        label_21 = new QLabel(widget);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(30, 280, 81, 21));
        label_22 = new QLabel(widget);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(10, 320, 111, 31));
        ajouter = new QPushButton(widget);
        ajouter->setObjectName(QStringLiteral("ajouter"));
        ajouter->setGeometry(QRect(40, 360, 93, 28));
        nbr_places = new QLineEdit(widget);
        nbr_places->setObjectName(QStringLiteral("nbr_places"));
        nbr_places->setGeometry(QRect(130, 220, 113, 22));
        le_kilometrage = new QLineEdit(widget);
        le_kilometrage->setObjectName(QStringLiteral("le_kilometrage"));
        le_kilometrage->setGeometry(QRect(110, 280, 113, 22));
        nbr_passagers = new QLineEdit(widget);
        nbr_passagers->setObjectName(QStringLiteral("nbr_passagers"));
        nbr_passagers->setGeometry(QRect(130, 330, 113, 22));
        pb_modifier_3 = new QPushButton(widget);
        pb_modifier_3->setObjectName(QStringLiteral("pb_modifier_3"));
        pb_modifier_3->setGeometry(QRect(160, 360, 93, 28));
        pb_supprimer_3 = new QPushButton(widget);
        pb_supprimer_3->setObjectName(QStringLiteral("pb_supprimer_3"));
        pb_supprimer_3->setGeometry(QRect(280, 360, 93, 28));
        la_matricule = new QLineEdit(widget);
        la_matricule->setObjectName(QStringLiteral("la_matricule"));
        la_matricule->setGeometry(QRect(110, 170, 113, 22));
        AFFECTER = new QPushButton(widget);
        AFFECTER->setObjectName(QStringLiteral("AFFECTER"));
        AFFECTER->setGeometry(QRect(100, 420, 93, 28));
        comboBox = new QComboBox(widget);
        comboBox->setObjectName(QStringLiteral("comboBox"));
        comboBox->setGeometry(QRect(220, 430, 73, 22));
        label_23 = new QLabel(tab_5);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(40, 10, 431, 71));
        label_23->setStyleSheet(QLatin1String("font: 75 24pt \"Californian FB\";\n"
""));
        label_24 = new QLabel(tab_5);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(610, 10, 431, 71));
        label_24->setStyleSheet(QLatin1String("font: 75 24pt \"Californian FB\";\n"
""));
        pb_trier_matricule = new QPushButton(tab_5);
        pb_trier_matricule->setObjectName(QStringLiteral("pb_trier_matricule"));
        pb_trier_matricule->setGeometry(QRect(570, 460, 141, 28));
        pb_rechercher_2 = new QPushButton(tab_5);
        pb_rechercher_2->setObjectName(QStringLiteral("pb_rechercher_2"));
        pb_rechercher_2->setGeometry(QRect(850, 460, 141, 28));
        tableView = new QTableView(tab_5);
        tableView->setObjectName(QStringLiteral("tableView"));
        tableView->setGeometry(QRect(580, 90, 441, 341));
        tableView->setStyleSheet(QStringLiteral("background-color: rgb(0, 255, 255);"));
        pb_pdf_2 = new QPushButton(tab_5);
        pb_pdf_2->setObjectName(QStringLiteral("pb_pdf_2"));
        pb_pdf_2->setGeometry(QRect(730, 460, 111, 28));
        tabWidget_3->addTab(tab_5, QString());
        tab_6 = new QWidget();
        tab_6->setObjectName(QStringLiteral("tab_6"));
        plot_3 = new QCustomPlot(tab_6);
        plot_3->setObjectName(QStringLiteral("plot_3"));
        plot_3->setGeometry(QRect(60, 20, 1061, 631));
        tabWidget_3->addTab(tab_6, QString());
        stackedWidget->addWidget(page_3);
        page_5 = new QWidget();
        page_5->setObjectName(QStringLiteral("page_5"));
        tabWidget_5 = new QTabWidget(page_5);
        tabWidget_5->setObjectName(QStringLiteral("tabWidget_5"));
        tabWidget_5->setGeometry(QRect(70, 30, 1021, 481));
        QFont font;
        tabWidget_5->setFont(font);
        widget_2 = new QWidget();
        widget_2->setObjectName(QStringLiteral("widget_2"));
        groupBox_18 = new QGroupBox(widget_2);
        groupBox_18->setObjectName(QStringLiteral("groupBox_18"));
        groupBox_18->setGeometry(QRect(20, 50, 861, 411));
        label_37 = new QLabel(groupBox_18);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(20, 220, 56, 16));
        label_38 = new QLabel(groupBox_18);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(20, 110, 56, 16));
        label_39 = new QLabel(groupBox_18);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(20, 60, 56, 16));
        label_40 = new QLabel(groupBox_18);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(20, 280, 71, 16));
        label_41 = new QLabel(groupBox_18);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(20, 170, 56, 16));
        lineEdit_code = new QLineEdit(groupBox_18);
        lineEdit_code->setObjectName(QStringLiteral("lineEdit_code"));
        lineEdit_code->setGeometry(QRect(150, 220, 113, 22));
        lineEdit_id = new QLineEdit(groupBox_18);
        lineEdit_id->setObjectName(QStringLiteral("lineEdit_id"));
        lineEdit_id->setGeometry(QRect(150, 60, 113, 22));
        lineEdit_redandance = new QLineEdit(groupBox_18);
        lineEdit_redandance->setObjectName(QStringLiteral("lineEdit_redandance"));
        lineEdit_redandance->setGeometry(QRect(150, 270, 113, 22));
        pb_ajouter_trajet = new QPushButton(groupBox_18);
        pb_ajouter_trajet->setObjectName(QStringLiteral("pb_ajouter_trajet"));
        pb_ajouter_trajet->setGeometry(QRect(390, 140, 93, 28));
        label_42 = new QLabel(groupBox_18);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(16, 325, 71, 20));
        dateEdit = new QDateEdit(groupBox_18);
        dateEdit->setObjectName(QStringLiteral("dateEdit"));
        dateEdit->setGeometry(QRect(150, 330, 110, 16));
        comboBox_3 = new QComboBox(groupBox_18);
        comboBox_3->setObjectName(QStringLiteral("comboBox_3"));
        comboBox_3->setGeometry(QRect(150, 170, 111, 22));
        comboBox_4 = new QComboBox(groupBox_18);
        comboBox_4->setObjectName(QStringLiteral("comboBox_4"));
        comboBox_4->setGeometry(QRect(150, 110, 111, 22));
        label_43 = new QLabel(groupBox_18);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(280, 280, 47, 14));
        label_44 = new QLabel(groupBox_18);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(280, 230, 47, 14));
        tabWidget_5->addTab(widget_2, QString());
        widget_3 = new QWidget();
        widget_3->setObjectName(QStringLiteral("widget_3"));
        tableView_2 = new QTableView(widget_3);
        tableView_2->setObjectName(QStringLiteral("tableView_2"));
        tableView_2->setGeometry(QRect(90, 90, 256, 192));
        modifier = new QPushButton(widget_3);
        modifier->setObjectName(QStringLiteral("modifier"));
        modifier->setGeometry(QRect(80, 330, 93, 27));
        label_45 = new QLabel(widget_3);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(440, 80, 56, 16));
        label_46 = new QLabel(widget_3);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(440, 170, 56, 16));
        label_47 = new QLabel(widget_3);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(440, 110, 56, 16));
        label_48 = new QLabel(widget_3);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(440, 200, 91, 16));
        label_49 = new QLabel(widget_3);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(440, 140, 56, 16));
        lineEdit_id_2 = new QLineEdit(widget_3);
        lineEdit_id_2->setObjectName(QStringLiteral("lineEdit_id_2"));
        lineEdit_id_2->setGeometry(QRect(510, 80, 113, 22));
        lineEdit_code_2 = new QLineEdit(widget_3);
        lineEdit_code_2->setObjectName(QStringLiteral("lineEdit_code_2"));
        lineEdit_code_2->setGeometry(QRect(510, 170, 113, 22));
        lineEdit_red = new QLineEdit(widget_3);
        lineEdit_red->setObjectName(QStringLiteral("lineEdit_red"));
        lineEdit_red->setGeometry(QRect(510, 200, 113, 22));
        pushButton_trier_trajet = new QPushButton(widget_3);
        pushButton_trier_trajet->setObjectName(QStringLiteral("pushButton_trier_trajet"));
        pushButton_trier_trajet->setGeometry(QRect(230, 330, 75, 27));
        comboBox_2 = new QComboBox(widget_3);
        comboBox_2->setObjectName(QStringLiteral("comboBox_2"));
        comboBox_2->setGeometry(QRect(320, 350, 71, 25));
        pushButton_rechercher_trajet = new QPushButton(widget_3);
        pushButton_rechercher_trajet->setObjectName(QStringLiteral("pushButton_rechercher_trajet"));
        pushButton_rechercher_trajet->setGeometry(QRect(230, 370, 75, 27));
        dateEdit_2 = new QDateEdit(widget_3);
        dateEdit_2->setObjectName(QStringLiteral("dateEdit_2"));
        dateEdit_2->setGeometry(QRect(510, 240, 110, 22));
        label_50 = new QLabel(widget_3);
        label_50->setObjectName(QStringLiteral("label_50"));
        label_50->setGeometry(QRect(440, 240, 47, 14));
        pushButton_exporter_trajet = new QPushButton(widget_3);
        pushButton_exporter_trajet->setObjectName(QStringLiteral("pushButton_exporter_trajet"));
        pushButton_exporter_trajet->setGeometry(QRect(30, 40, 75, 23));
        pushButton_qrcode_trajet = new QPushButton(widget_3);
        pushButton_qrcode_trajet->setObjectName(QStringLiteral("pushButton_qrcode_trajet"));
        pushButton_qrcode_trajet->setGeometry(QRect(800, 340, 151, 23));
        comboBox_5 = new QComboBox(widget_3);
        comboBox_5->setObjectName(QStringLiteral("comboBox_5"));
        comboBox_5->setGeometry(QRect(510, 140, 111, 22));
        comboBox_6 = new QComboBox(widget_3);
        comboBox_6->setObjectName(QStringLiteral("comboBox_6"));
        comboBox_6->setGeometry(QRect(510, 110, 111, 22));
        label_51 = new QLabel(widget_3);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(630, 210, 47, 14));
        label_52 = new QLabel(widget_3);
        label_52->setObjectName(QStringLiteral("label_52"));
        label_52->setGeometry(QRect(630, 180, 47, 14));
        label_qrcode = new QLabel(widget_3);
        label_qrcode->setObjectName(QStringLiteral("label_qrcode"));
        label_qrcode->setGeometry(QRect(810, 180, 131, 141));
        tabWidget_5->addTab(widget_3, QString());
        tab_9 = new QWidget();
        tab_9->setObjectName(QStringLiteral("tab_9"));
        label_53 = new QLabel(tab_9);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(160, 170, 56, 21));
        lineEdit_2 = new QLineEdit(tab_9);
        lineEdit_2->setObjectName(QStringLiteral("lineEdit_2"));
        lineEdit_2->setGeometry(QRect(220, 170, 113, 22));
        supprimer = new QPushButton(tab_9);
        supprimer->setObjectName(QStringLiteral("supprimer"));
        supprimer->setGeometry(QRect(430, 170, 93, 28));
        tabWidget_5->addTab(tab_9, QString());
        tab_10 = new QWidget();
        tab_10->setObjectName(QStringLiteral("tab_10"));
        widget_4 = new QWidget(tab_10);
        widget_4->setObjectName(QStringLiteral("widget_4"));
        widget_4->setGeometry(QRect(80, 20, 881, 421));
        tabWidget_5->addTab(tab_10, QString());
        stackedWidget->addWidget(page_5);
        page_6 = new QWidget();
        page_6->setObjectName(QStringLiteral("page_6"));
        tabWidget_6 = new QTabWidget(page_6);
        tabWidget_6->setObjectName(QStringLiteral("tabWidget_6"));
        tabWidget_6->setGeometry(QRect(60, 10, 1001, 511));
        tabWidget_6->setProperty("title", QVariant(QStringLiteral("")));
        Ajouter = new QWidget();
        Ajouter->setObjectName(QStringLiteral("Ajouter"));
        groupBox_19 = new QGroupBox(Ajouter);
        groupBox_19->setObjectName(QStringLiteral("groupBox_19"));
        groupBox_19->setGeometry(QRect(100, 20, 851, 451));
        label_54 = new QLabel(groupBox_19);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(50, 20, 47, 14));
        label_55 = new QLabel(groupBox_19);
        label_55->setObjectName(QStringLiteral("label_55"));
        label_55->setGeometry(QRect(50, 50, 47, 14));
        label_56 = new QLabel(groupBox_19);
        label_56->setObjectName(QStringLiteral("label_56"));
        label_56->setGeometry(QRect(10, 110, 81, 20));
        label_57 = new QLabel(groupBox_19);
        label_57->setObjectName(QStringLiteral("label_57"));
        label_57->setGeometry(QRect(20, 80, 71, 20));
        le_ID = new QLineEdit(groupBox_19);
        le_ID->setObjectName(QStringLiteral("le_ID"));
        le_ID->setGeometry(QRect(100, 20, 113, 20));
        le_Prix = new QLineEdit(groupBox_19);
        le_Prix->setObjectName(QStringLiteral("le_Prix"));
        le_Prix->setGeometry(QRect(100, 50, 113, 20));
        le_Horaire_entr = new QLineEdit(groupBox_19);
        le_Horaire_entr->setObjectName(QStringLiteral("le_Horaire_entr"));
        le_Horaire_entr->setGeometry(QRect(100, 80, 113, 20));
        le_Horaire_arr = new QLineEdit(groupBox_19);
        le_Horaire_arr->setObjectName(QStringLiteral("le_Horaire_arr"));
        le_Horaire_arr->setGeometry(QRect(100, 110, 113, 20));
        pb_ajouter_4 = new QPushButton(groupBox_19);
        pb_ajouter_4->setObjectName(QStringLiteral("pb_ajouter_4"));
        pb_ajouter_4->setGeometry(QRect(74, 140, 141, 23));
        le_ID_2 = new QLineEdit(groupBox_19);
        le_ID_2->setObjectName(QStringLiteral("le_ID_2"));
        le_ID_2->setGeometry(QRect(100, 180, 113, 20));
        le_Prix_2 = new QLineEdit(groupBox_19);
        le_Prix_2->setObjectName(QStringLiteral("le_Prix_2"));
        le_Prix_2->setGeometry(QRect(100, 210, 113, 20));
        le_Horaire_entr_2 = new QLineEdit(groupBox_19);
        le_Horaire_entr_2->setObjectName(QStringLiteral("le_Horaire_entr_2"));
        le_Horaire_entr_2->setGeometry(QRect(100, 240, 113, 20));
        le_Horaire_arr_2 = new QLineEdit(groupBox_19);
        le_Horaire_arr_2->setObjectName(QStringLiteral("le_Horaire_arr_2"));
        le_Horaire_arr_2->setGeometry(QRect(100, 270, 113, 20));
        pb_modifier_5 = new QPushButton(groupBox_19);
        pb_modifier_5->setObjectName(QStringLiteral("pb_modifier_5"));
        pb_modifier_5->setGeometry(QRect(34, 300, 91, 23));
        label_58 = new QLabel(groupBox_19);
        label_58->setObjectName(QStringLiteral("label_58"));
        label_58->setGeometry(QRect(50, 180, 47, 14));
        label_59 = new QLabel(groupBox_19);
        label_59->setObjectName(QStringLiteral("label_59"));
        label_59->setGeometry(QRect(50, 210, 47, 14));
        label_60 = new QLabel(groupBox_19);
        label_60->setObjectName(QStringLiteral("label_60"));
        label_60->setGeometry(QRect(30, 240, 61, 16));
        label_61 = new QLabel(groupBox_19);
        label_61->setObjectName(QStringLiteral("label_61"));
        label_61->setGeometry(QRect(30, 270, 61, 16));
        tab_ticket_2 = new QTableView(groupBox_19);
        tab_ticket_2->setObjectName(QStringLiteral("tab_ticket_2"));
        tab_ticket_2->setGeometry(QRect(230, 20, 421, 301));
        pb_supp_2 = new QPushButton(groupBox_19);
        pb_supp_2->setObjectName(QStringLiteral("pb_supp_2"));
        pb_supp_2->setGeometry(QRect(140, 300, 75, 23));
        pb_recherche_ID_2 = new QPushButton(groupBox_19);
        pb_recherche_ID_2->setObjectName(QStringLiteral("pb_recherche_ID_2"));
        pb_recherche_ID_2->setGeometry(QRect(320, 320, 101, 23));
        lineEdit_3 = new QLineEdit(groupBox_19);
        lineEdit_3->setObjectName(QStringLiteral("lineEdit_3"));
        lineEdit_3->setGeometry(QRect(430, 320, 113, 20));
        pb_recherche_PRIX_2 = new QPushButton(groupBox_19);
        pb_recherche_PRIX_2->setObjectName(QStringLiteral("pb_recherche_PRIX_2"));
        pb_recherche_PRIX_2->setGeometry(QRect(320, 350, 111, 23));
        lineEdit_4 = new QLineEdit(groupBox_19);
        lineEdit_4->setObjectName(QStringLiteral("lineEdit_4"));
        lineEdit_4->setGeometry(QRect(440, 350, 113, 20));
        pb_recherche_horaire_entr_2 = new QPushButton(groupBox_19);
        pb_recherche_horaire_entr_2->setObjectName(QStringLiteral("pb_recherche_horaire_entr_2"));
        pb_recherche_horaire_entr_2->setGeometry(QRect(320, 380, 121, 23));
        lineEdit_5 = new QLineEdit(groupBox_19);
        lineEdit_5->setObjectName(QStringLiteral("lineEdit_5"));
        lineEdit_5->setGeometry(QRect(450, 380, 113, 20));
        on_pb_trier_ticket = new QPushButton(groupBox_19);
        on_pb_trier_ticket->setObjectName(QStringLiteral("on_pb_trier_ticket"));
        on_pb_trier_ticket->setGeometry(QRect(10, 330, 75, 23));
        comboBox_7 = new QComboBox(groupBox_19);
        comboBox_7->setObjectName(QStringLiteral("comboBox_7"));
        comboBox_7->setGeometry(QRect(10, 360, 121, 22));
        ticketVIP = new QPushButton(groupBox_19);
        ticketVIP->setObjectName(QStringLiteral("ticketVIP"));
        ticketVIP->setGeometry(QRect(180, 360, 75, 23));
        tabWidget_6->addTab(Ajouter, QString());
        tab_11 = new QWidget();
        tab_11->setObjectName(QStringLiteral("tab_11"));
        plot_5 = new QCustomPlot(tab_11);
        plot_5->setObjectName(QStringLiteral("plot_5"));
        plot_5->setGeometry(QRect(10, 10, 721, 491));
        tabWidget_6->addTab(tab_11, QString());
        stackedWidget->addWidget(page_6);
        gestionmetro = new QPushButton(centralwidget);
        gestionmetro->setObjectName(QStringLiteral("gestionmetro"));
        gestionmetro->setGeometry(QRect(590, 10, 93, 29));
        gestionstation = new QPushButton(centralwidget);
        gestionstation->setObjectName(QStringLiteral("gestionstation"));
        gestionstation->setGeometry(QRect(360, 10, 93, 29));
        gestionticket = new QPushButton(centralwidget);
        gestionticket->setObjectName(QStringLiteral("gestionticket"));
        gestionticket->setGeometry(QRect(830, 10, 93, 29));
        gestionclient = new QPushButton(centralwidget);
        gestionclient->setObjectName(QStringLiteral("gestionclient"));
        gestionclient->setGeometry(QRect(250, 10, 93, 29));
        gestionpersonnel = new QPushButton(centralwidget);
        gestionpersonnel->setObjectName(QStringLiteral("gestionpersonnel"));
        gestionpersonnel->setGeometry(QRect(470, 10, 93, 29));
        gestiontrajet = new QPushButton(centralwidget);
        gestiontrajet->setObjectName(QStringLiteral("gestiontrajet"));
        gestiontrajet->setGeometry(QRect(710, 10, 93, 29));
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QStringLiteral("menubar"));
        menubar->setGeometry(QRect(0, 0, 1479, 26));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QStringLiteral("statusbar"));
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        stackedWidget->setCurrentIndex(5);
        tabWidget->setCurrentIndex(0);
        tabWidget_4->setCurrentIndex(0);
        tabWidget_2->setCurrentIndex(0);
        tabWidget_3->setCurrentIndex(0);
        tabWidget_5->setCurrentIndex(0);
        tabWidget_6->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", Q_NULLPTR));
        groupBox_8->setTitle(QApplication::translate("MainWindow", "Ajouter", Q_NULLPTR));
        label_8->setText(QApplication::translate("MainWindow", "Identifiant", Q_NULLPTR));
        label_10->setText(QApplication::translate("MainWindow", "Nom", Q_NULLPTR));
        label_11->setText(QApplication::translate("MainWindow", "Prenom", Q_NULLPTR));
        label_12->setText(QApplication::translate("MainWindow", "Adresse", Q_NULLPTR));
        pb_ajouter->setText(QApplication::translate("MainWindow", "Ajouter", Q_NULLPTR));
        label_13->setText(QApplication::translate("MainWindow", "Nombre de ticket", Q_NULLPTR));
        pb_modifier->setText(QApplication::translate("MainWindow", "Modifier", Q_NULLPTR));
        label_14->setText(QApplication::translate("MainWindow", "Age", Q_NULLPTR));
        groupBox_9->setTitle(QApplication::translate("MainWindow", "Afficher les clients", Q_NULLPTR));
        groupBox_10->setTitle(QApplication::translate("MainWindow", "Supprimer un client", Q_NULLPTR));
        label_15->setText(QApplication::translate("MainWindow", "Identifiant", Q_NULLPTR));
        pb_supprimer->setText(QApplication::translate("MainWindow", "Supprimer", Q_NULLPTR));
        groupBox_12->setTitle(QApplication::translate("MainWindow", "Rechercher un client ", Q_NULLPTR));
        label_16->setText(QString());
        pb_rechercherclient->setText(QApplication::translate("MainWindow", "Rechercher", Q_NULLPTR));
        groupBox_13->setTitle(QApplication::translate("MainWindow", "Envoyer mail", Q_NULLPTR));
        pb_send->setText(QApplication::translate("MainWindow", "Envoyer", Q_NULLPTR));
        pb_export_excel->setText(QApplication::translate("MainWindow", "Export", Q_NULLPTR));
        pb_trierclient->setText(QApplication::translate("MainWindow", "Trier ", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("MainWindow", "Ajouter un client", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(tab_4), QApplication::translate("MainWindow", "Statistique", Q_NULLPTR));
        groupBox_7->setTitle(QApplication::translate("MainWindow", "Ajout", Q_NULLPTR));
        label_25->setText(QApplication::translate("MainWindow", "Nom", Q_NULLPTR));
        label_26->setText(QApplication::translate("MainWindow", "Adresse", Q_NULLPTR));
        label_27->setText(QApplication::translate("MainWindow", "capacite", Q_NULLPTR));
        pb_ajouter_station->setText(QApplication::translate("MainWindow", "Ajouter", Q_NULLPTR));
        label_28->setText(QApplication::translate("MainWindow", "region", Q_NULLPTR));
        comboBox_nom->clear();
        comboBox_nom->insertItems(0, QStringList()
         << QApplication::translate("MainWindow", "Bizerte", Q_NULLPTR)
         << QApplication::translate("MainWindow", "Tunis", Q_NULLPTR)
         << QApplication::translate("MainWindow", "Nabeul", Q_NULLPTR)
         << QApplication::translate("MainWindow", "Sousse", Q_NULLPTR)
         << QApplication::translate("MainWindow", "Sfax", Q_NULLPTR)
         << QApplication::translate("MainWindow", "Gabes", Q_NULLPTR)
        );
        groupBox_15->setTitle(QApplication::translate("MainWindow", "Suppression", Q_NULLPTR));
        label_29->setText(QApplication::translate("MainWindow", "Nom", Q_NULLPTR));
        pb_supprimer_station->setText(QApplication::translate("MainWindow", "Supprimer", Q_NULLPTR));
        groupBox_16->setTitle(QApplication::translate("MainWindow", "Affichage", Q_NULLPTR));
        comboBox_affichage->clear();
        comboBox_affichage->insertItems(0, QStringList()
         << QApplication::translate("MainWindow", "tri par capacite croissante", Q_NULLPTR)
         << QApplication::translate("MainWindow", "tri par capacite decroissante", Q_NULLPTR)
         << QApplication::translate("MainWindow", "tri par nom croissant", Q_NULLPTR)
         << QApplication::translate("MainWindow", "tri par nom decroissant", Q_NULLPTR)
        );
        label_30->setText(QApplication::translate("MainWindow", "Nom", Q_NULLPTR));
        label_31->setText(QApplication::translate("MainWindow", "capacite", Q_NULLPTR));
        label_32->setText(QApplication::translate("MainWindow", "region", Q_NULLPTR));
        checkBox_nom->setText(QString());
        checkBox_capacite->setText(QString());
        checkBox_region->setText(QString());
        pb_recherche->setText(QApplication::translate("MainWindow", "rechercher", Q_NULLPTR));
        pb_tri_station->setText(QApplication::translate("MainWindow", "tri", Q_NULLPTR));
        groupBox_17->setTitle(QApplication::translate("MainWindow", "Modification", Q_NULLPTR));
        label_33->setText(QApplication::translate("MainWindow", "nom", Q_NULLPTR));
        label_34->setText(QApplication::translate("MainWindow", "adresse", Q_NULLPTR));
        label_35->setText(QApplication::translate("MainWindow", "region", Q_NULLPTR));
        label_36->setText(QApplication::translate("MainWindow", "capacite", Q_NULLPTR));
        pb_modifier_station->setText(QApplication::translate("MainWindow", "Modifier", Q_NULLPTR));
        comboBox_nom_2->clear();
        comboBox_nom_2->insertItems(0, QStringList()
         << QApplication::translate("MainWindow", "Bizerte", Q_NULLPTR)
         << QApplication::translate("MainWindow", "Tunis", Q_NULLPTR)
         << QApplication::translate("MainWindow", "Nabeul", Q_NULLPTR)
         << QApplication::translate("MainWindow", "Sousse", Q_NULLPTR)
         << QApplication::translate("MainWindow", "Sfax", Q_NULLPTR)
         << QApplication::translate("MainWindow", "Gabes", Q_NULLPTR)
        );
        tabWidget_4->setTabText(tabWidget_4->indexOf(tab_7), QApplication::translate("MainWindow", "Ajouter station", Q_NULLPTR));
        tabWidget_4->setTabText(tabWidget_4->indexOf(tab_8), QApplication::translate("MainWindow", "Statistique", Q_NULLPTR));
        groupBox->setTitle(QApplication::translate("MainWindow", "ajout", Q_NULLPTR));
        label->setText(QApplication::translate("MainWindow", "l'identifinat", Q_NULLPTR));
        label_2->setText(QApplication::translate("MainWindow", "nom", Q_NULLPTR));
        label_3->setText(QApplication::translate("MainWindow", "prenom", Q_NULLPTR));
        label_4->setText(QApplication::translate("MainWindow", "nombre des heures minimal", Q_NULLPTR));
        label_5->setText(QApplication::translate("MainWindow", "type de m\303\251tier", Q_NULLPTR));
        label_7->setText(QApplication::translate("MainWindow", "salaire", Q_NULLPTR));
        pb_ajouter_2->setText(QApplication::translate("MainWindow", "ajouter", Q_NULLPTR));
        label_6->setText(QApplication::translate("MainWindow", "nombre des heures maximale", Q_NULLPTR));
        pb_modifier_2->setText(QApplication::translate("MainWindow", "modifier", Q_NULLPTR));
        groupBox_2->setTitle(QApplication::translate("MainWindow", "supperssion", Q_NULLPTR));
        label_17->setText(QApplication::translate("MainWindow", "id", Q_NULLPTR));
        pb_supprimer_2->setText(QApplication::translate("MainWindow", "supprimer", Q_NULLPTR));
        groupBox_4->setTitle(QApplication::translate("MainWindow", "rechercher", Q_NULLPTR));
        pb_rechercher->setText(QApplication::translate("MainWindow", "recherhcher", Q_NULLPTR));
        label_9->setText(QApplication::translate("MainWindow", "nom", Q_NULLPTR));
        groupBox_5->setTitle(QApplication::translate("MainWindow", "trier", Q_NULLPTR));
        pb_tri_nom->setText(QApplication::translate("MainWindow", "tri nom ", Q_NULLPTR));
        groupBox_6->setTitle(QApplication::translate("MainWindow", "notifier", Q_NULLPTR));
        pushButton->setText(QApplication::translate("MainWindow", "update", Q_NULLPTR));
        groupBox_3->setTitle(QApplication::translate("MainWindow", "afficher personnel", Q_NULLPTR));
        chatBtn->setText(QApplication::translate("MainWindow", "Chat", Q_NULLPTR));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab), QApplication::translate("MainWindow", "ajouter personnel", Q_NULLPTR));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_3), QApplication::translate("MainWindow", "statistique", Q_NULLPTR));
        label_18->setText(QApplication::translate("MainWindow", "Creer Metro", Q_NULLPTR));
        label_19->setText(QApplication::translate("MainWindow", "matricule:", Q_NULLPTR));
        label_20->setText(QApplication::translate("MainWindow", "nbr de places:", Q_NULLPTR));
        label_21->setText(QApplication::translate("MainWindow", "kilometrage:", Q_NULLPTR));
        label_22->setText(QApplication::translate("MainWindow", "nbr de passagers:", Q_NULLPTR));
        ajouter->setText(QApplication::translate("MainWindow", "ajouter", Q_NULLPTR));
        pb_modifier_3->setText(QApplication::translate("MainWindow", "modifier", Q_NULLPTR));
        pb_supprimer_3->setText(QApplication::translate("MainWindow", "supprimer", Q_NULLPTR));
        AFFECTER->setText(QApplication::translate("MainWindow", "affecter", Q_NULLPTR));
        label_23->setText(QApplication::translate("MainWindow", "Gestion M\303\251tro", Q_NULLPTR));
        label_24->setText(QApplication::translate("MainWindow", "Bienvenue", Q_NULLPTR));
        pb_trier_matricule->setText(QApplication::translate("MainWindow", "trier matricules", Q_NULLPTR));
        pb_rechercher_2->setText(QApplication::translate("MainWindow", "recherche matricule", Q_NULLPTR));
        pb_pdf_2->setText(QApplication::translate("MainWindow", "Imprimer pdf", Q_NULLPTR));
        tabWidget_3->setTabText(tabWidget_3->indexOf(tab_5), QApplication::translate("MainWindow", "GESTION", Q_NULLPTR));
        tabWidget_3->setTabText(tabWidget_3->indexOf(tab_6), QApplication::translate("MainWindow", "Statistiques", Q_NULLPTR));
        groupBox_18->setTitle(QApplication::translate("MainWindow", "Ajout", Q_NULLPTR));
        label_37->setText(QApplication::translate("MainWindow", "Prix", Q_NULLPTR));
        label_38->setText(QApplication::translate("MainWindow", "Depart", Q_NULLPTR));
        label_39->setText(QApplication::translate("MainWindow", "ID", Q_NULLPTR));
        label_40->setText(QApplication::translate("MainWindow", "Dur\303\251e", Q_NULLPTR));
        label_41->setText(QApplication::translate("MainWindow", "Terminus", Q_NULLPTR));
        pb_ajouter_trajet->setText(QApplication::translate("MainWindow", "Ajouter", Q_NULLPTR));
        label_42->setText(QApplication::translate("MainWindow", "Date trajet", Q_NULLPTR));
        label_43->setText(QApplication::translate("MainWindow", "min", Q_NULLPTR));
        label_44->setText(QApplication::translate("MainWindow", "DT", Q_NULLPTR));
        tabWidget_5->setTabText(tabWidget_5->indexOf(widget_2), QApplication::translate("MainWindow", "Ajouter trajet", Q_NULLPTR));
        modifier->setText(QApplication::translate("MainWindow", "modifier", Q_NULLPTR));
        label_45->setText(QApplication::translate("MainWindow", "id", Q_NULLPTR));
        label_46->setText(QApplication::translate("MainWindow", "Prix", Q_NULLPTR));
        label_47->setText(QApplication::translate("MainWindow", "depart", Q_NULLPTR));
        label_48->setText(QApplication::translate("MainWindow", "Dur\303\251e", Q_NULLPTR));
        label_49->setText(QApplication::translate("MainWindow", "terminus", Q_NULLPTR));
        pushButton_trier_trajet->setText(QApplication::translate("MainWindow", "trier", Q_NULLPTR));
        comboBox_2->clear();
        comboBox_2->insertItems(0, QStringList()
         << QApplication::translate("MainWindow", "par ID", Q_NULLPTR)
         << QApplication::translate("MainWindow", "par prix", Q_NULLPTR)
         << QApplication::translate("MainWindow", "par dur\303\251e", Q_NULLPTR)
        );
        pushButton_rechercher_trajet->setText(QApplication::translate("MainWindow", "recherche", Q_NULLPTR));
        label_50->setText(QApplication::translate("MainWindow", "date", Q_NULLPTR));
        pushButton_exporter_trajet->setText(QApplication::translate("MainWindow", "Export txt", Q_NULLPTR));
        pushButton_qrcode_trajet->setText(QApplication::translate("MainWindow", "QR code", Q_NULLPTR));
        label_51->setText(QApplication::translate("MainWindow", "min", Q_NULLPTR));
        label_52->setText(QApplication::translate("MainWindow", "DT", Q_NULLPTR));
        label_qrcode->setText(QString());
        tabWidget_5->setTabText(tabWidget_5->indexOf(widget_3), QApplication::translate("MainWindow", "Affichage/Gestion trajet", Q_NULLPTR));
        label_53->setText(QApplication::translate("MainWindow", "ID", Q_NULLPTR));
        supprimer->setText(QApplication::translate("MainWindow", "supprimer", Q_NULLPTR));
        tabWidget_5->setTabText(tabWidget_5->indexOf(tab_9), QApplication::translate("MainWindow", "supprimer trajet", Q_NULLPTR));
        tabWidget_5->setTabText(tabWidget_5->indexOf(tab_10), QApplication::translate("MainWindow", "Statistiques", Q_NULLPTR));
        tabWidget_6->setProperty("Modifier les tickets", QVariant(QString()));
        tabWidget_6->setProperty("page", QVariant(QString()));
        tabWidget_6->setProperty("Page", QVariant(QString()));
        tabWidget_6->setProperty("tab_ticket", QVariant(QString()));
        tabWidget_6->setProperty("Ajouter une ticket", QVariant(QString()));
        Ajouter->setProperty("page", QVariant(QString()));
        Ajouter->setProperty("Ajouter une ticket", QVariant(QString()));
        groupBox_19->setTitle(QApplication::translate("MainWindow", "Cr\303\251ation d'une ticket", Q_NULLPTR));
        label_54->setText(QApplication::translate("MainWindow", "ID", Q_NULLPTR));
        label_55->setText(QApplication::translate("MainWindow", "Prix", Q_NULLPTR));
        label_56->setText(QApplication::translate("MainWindow", "Horaire arr", Q_NULLPTR));
        label_57->setText(QApplication::translate("MainWindow", "Horaire entr", Q_NULLPTR));
        pb_ajouter_4->setText(QApplication::translate("MainWindow", "Ajouter une Ticket", Q_NULLPTR));
        le_Prix_2->setProperty("Ajouter une ticket", QVariant(QString()));
        pb_modifier_5->setText(QApplication::translate("MainWindow", "Mettre \303\240 jour", Q_NULLPTR));
        label_58->setText(QApplication::translate("MainWindow", "ID", Q_NULLPTR));
        label_59->setText(QApplication::translate("MainWindow", "Prix", Q_NULLPTR));
        label_60->setText(QApplication::translate("MainWindow", "Horaire entr", Q_NULLPTR));
        label_61->setText(QApplication::translate("MainWindow", "Horaire arr", Q_NULLPTR));
        tab_ticket_2->setProperty("afficher", QVariant(QString()));
        pb_supp_2->setText(QApplication::translate("MainWindow", "Supprimer", Q_NULLPTR));
        pb_recherche_ID_2->setText(QApplication::translate("MainWindow", "Recherche ID", Q_NULLPTR));
        pb_recherche_PRIX_2->setText(QApplication::translate("MainWindow", "Recherche prix", Q_NULLPTR));
        pb_recherche_horaire_entr_2->setText(QApplication::translate("MainWindow", "recherche horaire", Q_NULLPTR));
        on_pb_trier_ticket->setText(QApplication::translate("MainWindow", "Tri", Q_NULLPTR));
        comboBox_7->clear();
        comboBox_7->insertItems(0, QStringList()
         << QApplication::translate("MainWindow", "par id", Q_NULLPTR)
         << QApplication::translate("MainWindow", "par prix", Q_NULLPTR)
         << QApplication::translate("MainWindow", "par horaire", Q_NULLPTR)
        );
        ticketVIP->setText(QApplication::translate("MainWindow", "ticket VIP", Q_NULLPTR));
        tabWidget_6->setTabText(tabWidget_6->indexOf(Ajouter), QApplication::translate("MainWindow", "Ticket", Q_NULLPTR));
        tabWidget_6->setTabText(tabWidget_6->indexOf(tab_11), QApplication::translate("MainWindow", "stats", Q_NULLPTR));
        gestionmetro->setText(QApplication::translate("MainWindow", "metro", Q_NULLPTR));
        gestionstation->setText(QApplication::translate("MainWindow", "station", Q_NULLPTR));
        gestionticket->setText(QApplication::translate("MainWindow", "ticket", Q_NULLPTR));
        gestionclient->setText(QApplication::translate("MainWindow", "client", Q_NULLPTR));
        gestionpersonnel->setText(QApplication::translate("MainWindow", "personnel", Q_NULLPTR));
        gestiontrajet->setText(QApplication::translate("MainWindow", "trajet", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
